apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: plane-https-redirect
  namespace: development-tools
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: home-lab
spec:
  redirectScheme:
    scheme: https
    permanent: true
