hostAPI: http://infisical-backend.platform-secrets.svc:8080/api

controllerManager:
  replicas: 1
  manager:
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        cpu: 250m
        memory: 256Mi

scopedNamespaces:
  - platform-secrets
  - observability

scopedRBAC: true
installCRDs: true

telemetry:
  serviceMonitor:
    enabled: false
