hostAPI: http://infisical-backend.platform-secrets.svc.cluster.local:8080/api

controllerManager:
  replicas: 1
  manager:
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        cpu: 250m
        memory: 256Mi

scopedNamespaces:
  - platform-secrets
  - platform-storage
  - observability
  - observability-tests
  - development-tools
  - ai-tools

scopedRBAC: true
installCRDs: true

telemetry:
  serviceMonitor:
    enabled: false
