{{- if and .Values.grpcui.enabled .Values.grpcui.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.grpcuiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.grpcuiLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.grpcui.auth.username }}:{{ .Values.grpcui.auth.htpasswdHash }}"
{{- end }}
