{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.jaegerUiName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.jaegerUiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.jaeger.uiService.type }}
  ports:
    - name: http
      port: {{ .Values.jaeger.uiService.port }}
      targetPort: ui
  selector:
    {{- include "platform-storage.jaegerLabels" . | nindent 4 }}
{{- end }}
