{{- if and .Values.jaeger.enabled .Values.jaeger.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.jaegerUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.jaegerUiLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.jaeger.auth.username }}:{{ .Values.jaeger.auth.htpasswdHash }}"
{{- end }}
