{{- if and .Values.kafka.enabled .Values.kafkaUi.enabled .Values.kafkaUi.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.kafkaUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.kafkaUiLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.kafkaUi.auth.username }}:{{ .Values.kafkaUi.auth.htpasswdHash }}"
{{- end }}
