{{- if and .Values.mailpit.enabled .Values.mailpit.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.mailpitUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mailpitUiLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.mailpit.auth.username }}:{{ .Values.mailpit.auth.htpasswdHash }}"
{{- end }}
