{{- if and .Values.minio.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.minioName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.minioLabels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.secretKey | quote }}
{{- end }}
