{{- if and .Values.mongodb.enabled .Values.mongoku.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.mongokuName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mongokuLabels" . | nindent 4 }}
type: Opaque
stringData:
  MONGOKU_DEFAULT_HOST: {{ printf "mongodb://%s:%s@%s.%s.svc.cluster.local:%v/admin?authSource=admin" .Values.mongodb.auth.rootUsername .Values.mongodb.auth.rootPassword (include "platform-storage.mongodbName" .) .Release.Namespace .Values.mongodb.service.port | quote }}
  MONGOKU_AUTH_BASIC: {{ printf "%s:%s" .Values.mongoku.auth.username .Values.mongoku.auth.password | quote }}
{{- end }}
