{{- if and .Values.mongodb.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.mongodbName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mongodbLabels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | quote }}
  MONGODB_MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}
  MONGODB_MONGO_INITDB_DATABASE: {{ .Values.mongodb.auth.database | quote }}
  MONGODB_APP_DATABASE: {{ .Values.mongodb.auth.database | quote }}
  MONGODB_APP_USERNAME: {{ .Values.mongodb.auth.username | quote }}
  MONGODB_APP_PASSWORD: {{ .Values.mongodb.auth.password | quote }}
{{- end }}
