{{- if and .Values.mongodb.enabled .Values.mongoku.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.mongokuName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mongokuLabels" . | nindent 4 }}
spec:
  type: {{ .Values.mongoku.service.type }}
  ports:
    - name: http
      port: {{ .Values.mongoku.service.port }}
      targetPort: http
  selector:
    {{- include "platform-storage.mongokuLabels" . | nindent 4 }}
{{- end }}
