{{- if and .Values.nats.enabled .Values.natsUi.enabled .Values.natsUi.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.natsUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsUiLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.natsUi.auth.username }}:{{ .Values.natsUi.auth.htpasswdHash }}"
{{- end }}
