{{- if and .Values.pgadmin.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.pgadminName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.pgadminLabels" . | nindent 4 }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.auth.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.auth.password | quote }}
{{- end }}
