{{- if and .Values.postgresql.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.postgresqlName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.postgresqlLabels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_DATABASE: {{ .Values.postgresql.auth.database | quote }}
  POSTGRESQL_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRESQL_POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
{{- end }}
