{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.rabbitmqName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.rabbitmqLabels" . | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
  selector:
    {{- include "platform-storage.rabbitmqLabels" . | nindent 4 }}
{{- end }}
