{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "platform-storage.rabbitmqName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- with .Values.rabbitmq.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "platform-storage.rabbitmqLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.rabbitmq.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.rabbitmq.metrics.serviceMonitor.scrapeTimeout }}
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod
    {{- if .Values.rabbitmq.metrics.detailed.enabled }}
    - port: metrics
      path: /metrics/detailed
      params:
        vhost:
          - {{ .Values.rabbitmq.metrics.detailed.vhost | quote }}
        family:
          {{- range .Values.rabbitmq.metrics.detailed.families }}
          - {{ . | quote }}
          {{- end }}
      interval: {{ .Values.rabbitmq.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.rabbitmq.metrics.serviceMonitor.scrapeTimeout }}
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod
      metricRelabelings:
        - targetLabel: rabbitmq_metric_scope
          replacement: detailed
    {{- end }}
{{- end }}
