{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platform-storage.rabbitmqName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.rabbitmqLabels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.rabbitmq.ingress.className }}
  {{- if .Values.rabbitmq.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.rabbitmq.ingress.host }}
      secretName: {{ .Values.rabbitmq.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.rabbitmq.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform-storage.rabbitmqName" . }}
                port:
                  number: {{ .Values.rabbitmq.service.managementPort }}
{{- end }}
