apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: temporal-postgresql
  namespace: development-tools
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: home-lab
    home-lab/managed-by: infisical
spec:
  hostAPI: http://infisical-backend.platform-secrets.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: platform-secrets
      secretsScope:
        projectSlug: home-lab
        envSlug: local
        secretsPath: /apps/development-tools/temporal
  managedSecretReference:
    secretName: temporal-postgresql
    secretNamespace: development-tools
    creationPolicy: Owner
