{{- if and .Values.ingress.enabled .Values.ingress.forceHttps }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "kubedeck.fullname" . }}-https-redirect
  labels:
    {{- include "kubedeck.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubedeck.fullname" . }}-http
  labels:
    {{- include "kubedeck.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s-https-redirect@kubernetescrd" .Release.Namespace (include "kubedeck.fullname" .) | quote }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "kubedeck.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
