{{- if .Values.grpcui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.grpcuiName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.grpcuiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.grpcui.service.type }}
  ports:
    - name: http
      port: {{ .Values.grpcui.service.port }}
      targetPort: http
  selector:
    {{- include "platform-storage.grpcuiLabels" . | nindent 4 }}
{{- end }}
