{{- if and .Values.kafka.enabled .Values.kafkaUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-storage.kafkaUiName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.kafkaUiLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "platform-storage.kafkaUiLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform-storage.labels" . | nindent 8 }}
        {{- include "platform-storage.kafkaUiLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUi.image.repository }}:{{ .Values.kafkaUi.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaUi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.kafkaUi.service.targetPort }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.kafkaUi.service.targetPort | quote }}
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ include "platform-storage.kafkaName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.service.internalPort }}"
            {{- if .Values.schemaRegistry.enabled }}
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "http://{{ include "platform-storage.schemaRegistryName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.schemaRegistry.service.port }}/apis/ccompat/v7"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.kafkaUi.resources | nindent 12 }}
{{- end }}
