{{- if .Values.mailpit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.mailpitUiName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mailpitUiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.mailpit.uiService.type }}
  ports:
    - name: http
      port: {{ .Values.mailpit.uiService.port }}
      targetPort: http
  selector:
    {{- include "platform-storage.mailpitLabels" . | nindent 4 }}
{{- end }}
