{{- if .Values.mailpit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secrets.infisical.com/auto-reload: "true"
  name: {{ include "platform-storage.mailpitName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mailpitLabels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "platform-storage.mailpitLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform-storage.labels" . | nindent 8 }}
        {{- include "platform-storage.mailpitLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mailpit
          image: "{{ .Values.mailpit.image.repository }}:{{ .Values.mailpit.image.tag }}"
          imagePullPolicy: {{ .Values.mailpit.image.pullPolicy }}
          env:
            - name: MP_DATABASE
              value: /data/mailpit.db
            {{- if .Values.mailpit.smtp.auth.enabled }}
            - name: MP_SMTP_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mailpit.smtp.auth.secretName }}
                  key: {{ .Values.mailpit.smtp.auth.secretKey }}
            - name: MP_SMTP_AUTH_ALLOW_INSECURE
              value: {{ .Values.mailpit.smtp.auth.allowInsecure | quote }}
            {{- end }}
          ports:
            - name: smtp
              containerPort: {{ .Values.mailpit.service.smtpPort }}
            - name: http
              containerPort: {{ .Values.mailpit.uiService.targetPort }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.mailpit.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "platform-storage.mailpitName" . }}
{{- end }}
