{{- if and .Values.nats.enabled .Values.nats.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "platform-storage.natsName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.nats.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "platform-storage.natsLabels" . | nindent 6 }}
{{- end }}
