{{- if and .Values.nats.enabled .Values.nats.monitoringIngress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.natsMonitoringName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsMonitoringLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.nats.monitoringIngress.auth.username }}:{{ .Values.nats.monitoringIngress.auth.htpasswdHash }}"
{{- end }}
