{{- if and .Values.nats.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.natsName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsLabels" . | nindent 4 }}
type: Opaque
stringData:
  NATS_ADMIN_USERNAME: {{ .Values.nats.auth.adminUsername | quote }}
  NATS_ADMIN_PASSWORD: {{ .Values.nats.auth.adminPassword | quote }}
  NATS_USERNAME: {{ .Values.nats.auth.username | quote }}
  NATS_PASSWORD: {{ .Values.nats.auth.password | quote }}
  NATS_FINANCE_USERNAME: {{ .Values.nats.auth.financeUsername | quote }}
  NATS_FINANCE_PASSWORD: {{ .Values.nats.auth.financePassword | quote }}
  NATS_CLUSTER_USERNAME: {{ .Values.nats.auth.clusterUsername | quote }}
  NATS_CLUSTER_PASSWORD: {{ .Values.nats.auth.clusterPassword | quote }}
{{- end }}
