{{- if and .Values.nats.enabled .Values.nats.monitoringIngress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.natsMonitoringName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsMonitoringLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: monitoring
  selector:
    {{- include "platform-storage.natsLabels" . | nindent 4 }}
{{- end }}
