{{- if and .Values.nats.enabled .Values.natsUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secrets.infisical.com/auto-reload: "true"
  name: {{ include "platform-storage.natsUiName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsUiLabels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "platform-storage.natsUiLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/contexts: {{ include (print $.Template.BasePath "/nats-ui-contexts-secret.yaml") . | sha256sum }}
      labels:
        {{- include "platform-storage.labels" . | nindent 8 }}
        {{- include "platform-storage.natsUiLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nats-ui
          image: "{{ .Values.natsUi.image.repository }}:{{ .Values.natsUi.image.tag }}"
          imagePullPolicy: {{ .Values.natsUi.image.pullPolicy }}
          args:
            - --db-path
            - /db
            - --nats-cli-contexts
            - /contexts
            - --log-output
            - /tmp/nui.log
          ports:
            - name: http
              containerPort: {{ .Values.natsUi.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.natsUi.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /db
            - name: contexts
              mountPath: /contexts
              readOnly: true
      volumes:
        - name: data
          {{- if .Values.natsUi.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "platform-storage.natsUiName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: contexts
          secret:
            secretName: {{ include "platform-storage.natsUiName" . }}-contexts
{{- end }}
