{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-storage.pgadminName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.pgadminLabels" . | nindent 4 }}
data:
  config_local.py: |
    ALLOW_SPECIAL_EMAIL_DOMAINS = ["local"]
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Platform PostgreSQL",
          "Group": "Platform",
          "Host": "{{ include "platform-storage.postgresqlName" . }}.{{ .Release.Namespace }}.svc.cluster.local",
          "Port": {{ .Values.postgresql.service.port }},
          "MaintenanceDB": "default",
          "Username": "admin",
          "ConnectionParameters": {
            "sslmode": "prefer",
            "connect_timeout": 10
          }
        }
      }
    }
{{- end }}
