{{- if and .Values.rabbitmq.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.rabbitmqName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.rabbitmqLabels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.auth.erlangCookie | quote }}
{{- end }}
