{{- if and .Values.redis.enabled .Values.redisCommander.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.redisCommanderName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.redisCommanderLabels" . | nindent 4 }}
type: Opaque
stringData:
  HTTP_USER: {{ .Values.redisCommander.auth.username | quote }}
  HTTP_PASSWORD: {{ .Values.redisCommander.auth.password | quote }}
  REDIS_HOSTS: "local:{{ include "platform-storage.redisName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.redis.service.port }}:0:{{ .Values.redis.auth.password }}"
{{- end }}
