{{- if and .Values.redis.enabled .Values.redisCommander.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-storage.redisCommanderName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.redisCommanderLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "platform-storage.redisCommanderLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-commander-secret.yaml") . | sha256sum }}
      labels:
        {{- include "platform-storage.labels" . | nindent 8 }}
        {{- include "platform-storage.redisCommanderLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis-commander
          image: "{{ .Values.redisCommander.image.repository }}:{{ .Values.redisCommander.image.tag }}"
          imagePullPolicy: {{ .Values.redisCommander.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.redisCommander.service.targetPort }}
          env:
            - name: HTTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-storage.redisCommanderName" . }}
                  key: REDIS_COMMANDER_HTTP_USER
            - name: HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-storage.redisCommanderName" . }}
                  key: REDIS_COMMANDER_HTTP_PASSWORD
            - name: REDIS_HOSTS
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-storage.redisCommanderName" . }}
                  key: REDIS_COMMANDER_REDIS_HOSTS
            - name: PORT
              value: {{ .Values.redisCommander.service.targetPort | quote }}
            - name: K8S_SIGTERM
              value: "1"
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.redisCommander.resources | nindent 12 }}
{{- end }}
