{{- if .Values.redis.enabled }}
{{- $redisAcl := default (dict) .Values.redis.acl }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "platform-storage.redisName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.redisLabels" . | nindent 4 }}
spec:
  serviceName: {{ include "platform-storage.redisName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "platform-storage.redisLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
      labels:
        {{- include "platform-storage.labels" . | nindent 8 }}
        {{- include "platform-storage.redisLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
          args:
            - --appendonly
            - "yes"
            - --aclfile
            - /etc/redis/users.acl
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-storage.redisName" . }}
                  key: REDIS_PASSWORD
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-storage.redisName" . }}
                  key: REDIS_REDISCLI_AUTH
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping | grep PONG
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping | grep PONG
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: acl
              mountPath: /etc/redis
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: acl
          secret:
            secretName: {{ include "platform-storage.redisName" . }}
            items:
              - key: {{ default "REDIS_ACL_FILE" $redisAcl.fileSecretKey }}
                path: users.acl
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}
