{{- if and .Values.kafka.enabled .Values.schemaRegistry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.schemaRegistryUiName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.schemaRegistryUiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.schemaRegistry.uiService.type }}
  ports:
    - name: http
      port: {{ .Values.schemaRegistry.uiService.port }}
      targetPort: http
  selector:
    {{- include "platform-storage.schemaRegistryUiLabels" . | nindent 4 }}
{{- end }}
