apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    home-lab/managed-by: infisical
spec:
  hostAPI: http://infisical-backend.platform-secrets.svc.cluster.local:8080/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: platform-secrets
      secretsScope:
        projectSlug: home-lab
        envSlug: local
        secretsPath: /apps/development-tools/n8n
  managedSecretReference:
    secretName: n8n
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
