apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: kubedeck-agent-auth
  labels:
    {{- include "kubedeck-agent.labels" . | nindent 4 }}
    home-lab/managed-by: infisical
spec:
  hostAPI: http://infisical-backend.platform-secrets.svc.cluster.local:8080/api
  syncConfig:
    resyncInterval: 1m
    instantUpdates: false
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: platform-secrets
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        envSlug: {{ .Values.infisical.envSlug | quote }}
        secretsPath: /apps/development-tools/kubedeck-agent
  managedSecretReference:
    secretName: kubedeck-agent-auth
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
    template:
      includeAllSecrets: true
