apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-storage
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-secrets
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-tests
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: development-tools
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-tools
  labels:
    app.kubernetes.io/part-of: home-lab
    home-lab/category: ai
