image:
  repository: chrislusf/seaweedfs
  tag: "4.48@sha256:4e61d15fd35994cb1e43e1e553dff106794841fd9a99ade2fc8c8bfce4d7872d"
  pullPolicy: IfNotPresent

bucket: default
credentials:
  existingSecret: minio
  accessKey: MINIO_ACCESS_KEY
  secretKey: MINIO_SECRET_KEY

persistence:
  storageClass: standard
  size: 8Gi

service:
  port: 8333

ingress:
  enabled: true
  className: traefik
  host: s3.local.dev
  tlsSecretName: local-dev-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 2Gi
