apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperclip.fullname" . }}-postgresql
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "paperclip.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
