{{- if and .Values.grpcui.enabled .Values.grpcui.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "platform-storage.grpcuiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.grpcuiLabels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "platform-storage.grpcuiName" . }}-basic-auth
{{- end }}
