{{- if and .Values.kafka.enabled .Values.kafkaUi.enabled .Values.kafkaUi.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "platform-storage.kafkaUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.kafkaUiLabels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "platform-storage.kafkaUiName" . }}-basic-auth
{{- end }}
