{{- if and .Values.minio.enabled .Values.minio.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platform-storage.minioName" . }}-console
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.minioLabels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.minio.ingress.className }}
  {{- if .Values.minio.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.minio.ingress.consoleHost }}
      secretName: {{ .Values.minio.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.minio.ingress.consoleHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform-storage.minioName" . }}
                port:
                  name: console
{{- end }}
