{{- if and .Values.mongodb.enabled .Values.mongoku.enabled .Values.mongoku.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.mongokuName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mongokuLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.mongoku.auth.username }}:{{ .Values.mongoku.auth.htpasswdHash }}"
{{- end }}
