{{- if and .Values.mongodb.enabled .Values.mongoku.enabled .Values.mongoku.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "platform-storage.mongokuName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.mongokuLabels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "platform-storage.mongokuName" . }}-basic-auth
{{- end }}
