{{- if and .Values.nats.enabled .Values.nats.prometheusExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-storage.natsMetricsName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsMetricsLabels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.nats.prometheusExporter.port }}
      targetPort: metrics
  selector:
    {{- include "platform-storage.natsLabels" . | nindent 4 }}
{{- end }}
