{{- if and .Values.nats.enabled .Values.natsUi.enabled .Values.natsUi.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "platform-storage.natsUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsUiLabels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "platform-storage.natsUiName" . }}-basic-auth
{{- end }}
