{{- if and .Values.nats.enabled .Values.natsUi.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.natsUiName" . }}-contexts
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.natsUiLabels" . | nindent 4 }}
type: Opaque
stringData:
  local.json: |
    {
      "description": "Local NATS",
      "url": "nats://{{ include "platform-storage.natsName" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.nats.service.clientPort }}",
      "user": {{ .Values.nats.auth.adminUsername | quote }},
      "password": {{ .Values.nats.auth.adminPassword | quote }},
      "jetstream_domain": "",
      "jetstream_api_prefix": "",
      "jetstream_event_prefix": "",
      "inbox_prefix": "",
      "tls_first": false
    }
{{- end }}
