{{- if and .Values.redis.enabled .Values.redisCommander.enabled .Values.redisCommander.ingress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.redisCommanderName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.redisCommanderLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.redisCommander.auth.username }}:{{ .Values.redisCommander.auth.htpasswdHash }}"
{{- end }}
