{{- if and .Values.redis.enabled .Values.redisCommander.enabled .Values.redisCommander.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platform-storage.redisCommanderName" . }}
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.redisCommanderLabels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "platform-storage.redisCommanderName" . }}-basic-auth@kubernetescrd
spec:
  ingressClassName: {{ .Values.redisCommander.ingress.className }}
  {{- if .Values.redisCommander.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.redisCommander.ingress.host }}
      secretName: {{ .Values.redisCommander.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.redisCommander.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform-storage.redisCommanderName" . }}
                port:
                  number: {{ .Values.redisCommander.service.port }}
{{- end }}
