{{- if and .Values.kafka.enabled .Values.schemaRegistry.enabled .Values.schemaRegistry.uiIngress.enabled .Values.inlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-storage.schemaRegistryUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.schemaRegistryUiLabels" . | nindent 4 }}
type: Opaque
stringData:
  users: "{{ .Values.schemaRegistry.auth.username }}:{{ .Values.schemaRegistry.auth.htpasswdHash }}"
{{- end }}
