{{- if and .Values.kafka.enabled .Values.schemaRegistry.enabled .Values.schemaRegistry.uiIngress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "platform-storage.schemaRegistryUiName" . }}-basic-auth
  labels:
    {{- include "platform-storage.labels" . | nindent 4 }}
    {{- include "platform-storage.schemaRegistryUiLabels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "platform-storage.schemaRegistryUiName" . }}-basic-auth
{{- end }}
