{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: kubedeck-agent-auth
  labels:
    {{- include "kubedeck-agent.labels" . | nindent 4 }}
    home-lab/managed-by: infisical
spec:
  hostAPI: {{ .Values.infisical.hostAPI | quote }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsSecretName | quote }}
        secretNamespace: {{ .Values.infisical.credentialsSecretNamespace | quote }}
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        envSlug: {{ .Values.infisical.envSlug | quote }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}
  managedSecretReference:
    secretName: kubedeck-agent-auth
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
{{- end }}
