apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    home-lab/managed-by: infisical
spec:
  hostAPI: http://infisical-backend.platform-secrets.svc.cluster.local:8080/api
  syncConfig:
    resyncInterval: 1m
    instantUpdates: false
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: platform-secrets
      secretsScope:
        projectSlug: home-lab
        envSlug: local
        secretsPath: /apps/observability/grafana
  managedSecretReference:
    secretName: grafana-admin
    secretNamespace: {{ include "grafana.namespace" . }}
    creationPolicy: Owner
    template:
      includeAllSecrets: true
