apiVersion: v1
kind: Service
metadata:
  name: home-lab-dns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: local-dns
    app.kubernetes.io/part-of: home-lab
spec:
  type: LoadBalancer
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
