apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    home-lab/managed-by: infisical
spec:
  hostAPI: {{ required "infisical.hostAPI is required" .Values.infisical.hostAPI | quote }}
  syncConfig:
    resyncInterval: 1m
    instantUpdates: false
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ required "infisical.credentialsSecretName is required" .Values.infisical.credentialsSecretName | quote }}
        secretNamespace: {{ required "infisical.credentialsSecretNamespace is required" .Values.infisical.credentialsSecretNamespace | quote }}
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        envSlug: {{ .Values.infisical.envSlug | quote }}
        secretsPath: {{ required "infisical.secretsPath is required" .Values.infisical.secretsPath | quote }}
  managedSecretReference:
    secretName: grafana-admin
    secretNamespace: {{ include "grafana.namespace" . }}
    creationPolicy: Owner
    template:
      includeAllSecrets: true
